import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "../components/Header";
import { SourceProvider } from "../context/SourceContext"; // Import the SourceProvider
import { DestinationProvider } from "../context/DestinationContext"; // Import the DestinationProvider

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          {/* Wrap the app with SourceProvider and DestinationProvider */}
          <SourceProvider>
            <DestinationProvider>
              {children} {/* All child components will have access to source and destination contexts */}
            </DestinationProvider>
          </SourceProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
